name: Crush Your Fears
favicon: null
layout_spectrum: 0.05878
typography_spectrum: 0.04681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#315676'
    - '#ffffff'
    - '#292930'
    - '#f1cd94'
    - '#82a0b4'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
