name: Crush Your Fears
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36028563091531396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#315676'
    - '#ffffff'
    - '#292930'
    - '#f1cd94'
    - '#82a0b4'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
